### PR TITLE
Improve support for transient simulations and outputting timestep data

### PR DESCRIPTION
**Pull request by magnaou**
Main changes:
- results methods (transient and steady version)
- new residual calculation
- other minor changes

**I -** alg.results(times=None):
- times=None is the default and returns ALL stored times
- times can be a numpy array or a list of scalars
- if times is a scalar, only the corresponding time step is returned
- send a warning if a non stored time step is requested

Example:
```
In [2]: alg.results(times=9).keys()
Out[2]: dict_keys(['pore.concentration@9'])

In [3]: alg.results(times=[10,13,12]).keys()
    WARNING: Time(s) [12 13] not stored. 
    SOURCE: openpnm.algorithms.TransientReactiveTransport.results 
    TIME STAMP: 2018-10-22 19:44:16,400    
Out[3]: dict_keys(['pore.concentration@10'])
```
**II -** Added the method alg._nbr_to_str(time):
- a method for converting a scalar into string in scientific (exponential) notation without the decimal point
- @jgostick should this be kept in the TransientReactiveTransport?

**III -** Transient algorithm output (stored) times:
- Now t_output can be a numpy array

**IV -** Compute the residual/relative tolerance: Get rid of the possible non conducting throats. Changes were made in ReactiveTransport, TransientReactiveTransport, and GenericTransport (@ma-sadeghi could you check lines 481 to 494 in GenericTransport?).

**V -** Added tests.

### CODE REVIEW

**Comment by jgostick** [comment]
Lines 306 to 308 in ReactiveTransport needs some though for 'non-conducting' throat values....also check other classes for same problem

**Comment by jgostick** [comment]
For `results`, change times arg to default to None, meaning all times, otherwise accept a scalar or list of scalars.

**Comment by magnaou** [comment]
I - alg.results(times=None):
- times=None is the default and returns ALL stored times
- times can be a numpy array or a list of scalars
- if times is a scalar, only the corresponding time step is returned
- send a warning if a non stored time step is requested

Example:
In [2]: alg.results(times=9).keys()
Out[2]: dict_keys(['pore.concentration@9'])

In [3]: alg.results(times=[10,13,12]).keys()
―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
    WARNING: Time(s) [12 13] not stored. 
    SOURCE: openpnm.algorithms.TransientReactiveTransport.results 
    TIME STAMP: 2018-10-22 19:44:16,400    
Out[3]: dict_keys(['pore.concentration@10'])

II - Added the method alg._nbr_to_str(time):
- a method for converting a scalar into string in scientific (exponential) notation without the decimal point
- @jgostick should this be kept in the TransientReactiveTransport?

III - Transient algorithm output (stored) times:
- Now t_output can be a numpy array

IV - Compute the residual/relative tolerance: Get rid of the possible non conducting throats. Changes were made in ReactiveTransport, TransientReactiveTransport, and GenericTransport (@ma-sadeghi could you check lines 481 to 489 in GenericTransport).

**Comment by jgostick** [comment]
I think we can/should catch the scientific notation in the array name, convert it to digits, then use that to name file.

**Comment by magnaou** [comment]
@jgostick you can see here (https://www.paraview.org/Wiki/Animating_legacy_VTK_file_series) the different patterns that Paraview interprets as time series with VTK files.

**Pull request merged**
