### PR TITLE
Fixed a bug in the late_pore_filling model

### PR DESCRIPTION
**Pull request by maghighi**
It was the same problem with the conduit conductance model. It was written with the old OpenPNM style.
In the new form, everything must be calculated for the phase, but only values of the physics should be returned.

### CODE REVIEW

**Comment by maghighi** [comment]
This PR fixes the same problem we had with conduit_conductance model. It was my bad I didn't catch it in the PR #394 . @jgostick, please check and merge it.

**Comment by jgostick** [comment]
Perhaps you can write some unit tests for these models while you're digging around in there?  :-D  You can copy my examples for the phase models

**Comment by maghighi** [comment]
I added tests for multphase models in the physics. It was a little tricky, especially checking the outputs of different conduit modes, but they seem to work.

**Comment by jgostick** [comment]
Awesome, now I know that @maghighi knows how to write a test, so anoint him our new test guru :-D

**Pull request merged**
