### PR TITLE
Updating travis and code coverage

### PR DESCRIPTION
**Pull request by jgostick**
Also, added python 3.5 coverage

### CODE REVIEW

**Comment by jgostick** [comment]
It's very important to get our code coverage back online.  I'm moving this up to a V1.5 milestone.

**Comment by jgostick** [comment]
I'm going to delete this PR.  I will start a new one that focuses on getting codecov working again instead of switching to back to coveralls

**Comment by bspellio** [comment]
Is there a specific reason you were dropping Python 3.3 support?

**Comment by jgostick** [comment]
I was feeling guilty about making travis work so hard to do all our builds, but (a) we install scikits-image from anaconda now, not source, so that shaves 5+ minutes off the build and (b) other projects build about 20 different envs so 3 is nothing.  I closed this branch anyway.

**Comment by bspellio** [comment]
:+1:

**Pull request closed without merging**
