### PR TITLE
Fix controller

### PR DESCRIPTION
**Pull request by maghighi**
This PR, includes two minor changes in the controller. There were two problems with ghost_object and clone_simulation methods. Now, they are fixed.

### CODE REVIEW

**Comment by maghighi** [comment]
As discussed with @jgostick last week, these changes take care of two minor problems in the clone_simulation and ghost_object. Travis Cl will probably show many failed tests, but none of them are related to these two.

**Comment by jgostick** [comment]
Maybe you should merge the 85%-test-coverage branch into this to fix all the errors?

**Comment by maghighi** [comment]
These errors are different than the 85% branch. Most of the failed tests in the develop branch are related to the 'print' and 'str'. I guess @bspellio is working on them.

**Comment by jgostick** [comment]
I recognize all those errors. I fixed ALL the failing tests last night (and removed 1 str test).  I'm sure that all your errors will go away if you merge it in.

**Comment by jgostick** [comment]
See, I told you!

**Comment by bspellio** [comment]
This diff is huge, we should merge it into `85-percent-test-coverage`

**Pull request merged**
