### PR TITLE
modified solver

### PR DESCRIPTION
**Pull request by maghighi**
This pull request addresses the issue #467. Also, the unit and integration tests have been modified according to the new changes.

### CODE REVIEW

**Comment by jgostick** [comment]
Why didn't Travis run the tests?

**Comment by maghighi** [comment]
I'm not sure. I ran all the tests locally and then made the pull request. But Travis didn't run the tests and I couldn't figure out why.

**Comment by jgostick** [comment]
This happened to me on the Empty Network PR, because I'd named two tests the same name (I think).  I'll check it out.

**Comment by jgostick** [comment]
Or perhaps it thinks nothing has changed since you just cut and pasted code around?

**Comment by maghighi** [comment]
I moved the code from generic_algorithm, but the code in the solver is totally different, because I had to remove the component from everywhere. Even if it was exactly the same, Travis should run the tests, because the fact that something runs properly in a generic class, does not guarantee that it can be run in its subclass.

**Pull request merged**
