### PR TITLE
Fix nernst planck examples

### LINKED ISSUE #2088: Nernst-Planck example scripts are broken (both 2d and 3d)
How did this happen? Don't we test the `scripts/` folder?

### PR DESCRIPTION
**Pull request by mkaguer**
Fixes #2088

### CODE REVIEW

**Comment by ma-sadeghi** [comment]
@mkaguer Hmm, so basically, reducing the number of iterations from 100 to 50 fixes the issue. This seems a bit strange to me. Why is it that if we continue iterating, instead of getting closer to the solution, we're moving away?

**Comment by mkaguer** [comment]
Hi @ma-sadeghi. As discussed the issue is using 'electroneutrality' assumption. I am pushing changes so that 'poisson' is used in this example. The user should be cautioned to use electroneutrality.

**Comment by ma-sadeghi** [comment]
Hey @mkaguer, the 3d version of the example works fine, but the 2d one still diverges. Could you please look into it? Thanks!

**Comment by mkaguer** [comment]
Hi @ma-sadeghi. I think I found the problem. The StickAndBall2D class was adding sphere and cylinder size factors. Shouldn't we be using circles and rectangles for the 2D case? I changed that and now it converges okay. Please let me know if this is not right.

**Pull request merged**
