### PR TITLE
Fix the boundary labeling problem

### PR DESCRIPTION
**Pull request by Ni2M**
#1575 fix the labeling problem to be consistent with the right hand rule.

### CODE REVIEW

**Comment by Ni2M** [comment]
It's breaking the examples and tests. I'll look into them to fix it.

**Comment by Ni2M** [comment]
The changes in labeling works. The test files mostly fail.
left
right
front
back
top
bottom

**Comment by jgostick** [comment]
Fixes #1575

**Comment by Ni2M** [comment]
The only Problem left is the pn.check_network_health output in [example tutorial advanced](https://github.com/PMEAL/OpenPNM/blob/dev/examples/tutorials/Intro%20to%20OpenPNM%20-%20Advanced.ipynb). When I run it locally on dev and on this branch, it gives me the same answer, but the ci test gives a different answer.

**Comment by ma-sadeghi** [comment]
> The only Problem left is the pn.check_network_health output in [example tutorial advanced](https://github.com/PMEAL/OpenPNM/blob/dev/examples/tutorials/Intro%20to%20OpenPNM%20-%20Advanced.ipynb). When I run it locally on dev and on this branch, it gives me the same answer, but the ci test gives a different answer.

How much of a difference are we talking about? Is it like a numerical error?

**Comment by Ni2M** [comment]
> 
> 
> > The only Problem left is the pn.check_network_health output in [example tutorial advanced](https://github.com/PMEAL/OpenPNM/blob/dev/examples/tutorials/Intro%20to%20OpenPNM%20-%20Advanced.ipynb). When I run it locally on dev and on this branch, it gives me the same answer, but the ci test gives a different answer.
> 
> How much of a difference are we talking about? Is it like a numerical error?

**Comment by Ni2M** [comment]
@ma-sadeghi The online results generates the same array, but without the data type (dtype=int) whereas on my local computer both branches generate the dtype as well when printing the arrays. I can ignore the output check for that cell in .ipynb file.

**Comment by Ni2M** [comment]
I think this branch is ready to merge, if the code factor is acceptable.

**Pull request merged**
