### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by jgostick**
This PR moves several files around.  Many things were moved into the docs/resources folder, and the sample extracted network was moved to test/fixtures

### CODE REVIEW

**Comment by bspellio** [comment]
So why are you keeping two copies of InvasionPercolationTimed? With one being int RST and another being a python file?

**Comment by jgostick** [comment]
still working on it....I guess we'll delete the .py file.  I need to copy
all of the other py files into rst code-blocks.


On Thu, Jun 25, 2015 at 10:02 AM, Brennan Spellacy <notifications@github.com

**Comment by bspellio** [comment]
This looks great @jgostick I think we're good to merge.

**Comment by jgostick** [comment]
ok, go for it.  I'm done.

**Pull request merged**
