### PR TITLE
Nonserializable check in models

### PR DESCRIPTION
**Pull request by jgostick**
Simple addition to the ModelsWrapper class init to ensure all model args, except for models themselves, are serializable.

### CODE REVIEW

**Comment by jgostick** [comment]
It seems there are 19 failed tests.  Most are due to passing in a phase object rather than a name, but there are a few that are literally designed to accept function, such as the symbol (sympy) source term models, and the generic pore/throat size models that accept a frozen scipy.stats models.  Hmmm.

**Comment by jgostick** [comment]
I have fixed the symbolic source term (backwards incompatibly), and it now works as I always thought it should.  It accepts a string describing the equation, and key word arguments.  Everything else is done internally.

Now I want to fix the generic pore size model.  I think it also needs to be done backwards incompatibly.  If we change the ``func`` argument to ``func_name``, and accept a string, we can then use ``getattr(scipy.stats, func_name)`` internally.  Simple to fix, but incompatible.

**Comment by jgostick** [comment]
This fixes #1743, as well as #1718

**Comment by jgostick** [comment]
This one will need some discussion.  It breaks backward compatibility for several models, and could pose an major annoyance to people by blocking the passing of numpy arrays to the models.  Although, I would argue that not being able to save the work to a PNM file is a greater annoyance.

**Comment by ma-sadeghi** [comment]
@jgostick Can we merge this?

**Pull request closed without merging**
