### PR TITLE
Pep8ification of OpenPNM

### PR DESCRIPTION
**Pull request by bspellio**
This PR addresses #334 and applies a stylistic consistency across all of OpenPNM, with a few exceptions, according to the PEP8 standard.
The exceptions are written in `tox.ini`, I decided to omit these files due to their incredible complexity and I didn't want to risk breaking any of these files, especially if we end up refactoring them

### CODE REVIEW

**Comment by jgostick** [comment]
I will ask James to clean up his messy algorithms.  What should I tell him
to do?

**Comment by maghighi** [comment]
I'll try to clean up GenericLinearTransport and GenericAlgorithm.

**Comment by bspellio** [comment]
@RodericDay @jgostick This branch should be ready to go. It's a lot to look at, so try to just scan over it just to assure that I'm not changing any functionality.

**Comment by bspellio** [comment]
@RodericDay @jgostick This branch should be ready to go. It's a lot to look at, so try to just scan over it just to assure that I'm not changing any functionality.

**Comment by jgostick** [comment]
You've changed about 100000 lines of code, so looking it over seems
impossible.  I thought that was why we have tests, so we don't have to look
at this sort of thing? :-D

**Comment by bspellio** [comment]
@jgostick of course, I was primarily referring to the `tox.ini` and `setup.py` because they have a few changes. The rest is pretty unimportant from an understanding perspective.

**Comment by RodericDay** [comment]
I think rather than scan it over, you should just run it with whatever you're working with currently, and see if anything breaks.

If it does, that means more tests need to be written and things worked out. Otherwise, greenlight the merge.

**Pull request merged**
