### PR TITLE
Mixed IP - Coop filling enhancement

### PR DESCRIPTION
**Pull request by TomTranter**

### CODE REVIEW

**Comment by TomTranter** [comment]
@jgostick this isn't finished and I think could be an algorithm model. I currently have 3 ways of doing the coop filling. Merging bulging interfaces (Hysteresis Paper), Merging creeping contact lines (Toni Paper) and analysis on the triple phase boundary - turned out to be really slow and not needed so will take out. It's conceivable that you might want to look for both the first two

**Comment by jgostick** [comment]
@TomTranter can you update me on this?  We are trying to get PRs and issues down to a bare minimum before the workshop at interpore, so making large push for the next few weeks.  Do we need a discussion to proceed?

**Comment by TomTranter** [comment]
Hey @jgostick sorry for the late reply. This one hasn't changed since my comment above I'm afraid. I ended up not really using coop filling for the paper with Toni. I don't have a lot of time to work on this right now but it's worth keeping and polishing a bit.

**Comment by TomTranter** [comment]
@jgostick I probably missed some discussion on this but what have we settled on for calling the throat.<something>_pressure? capillary, critical, entry? I'm putting the finishing touches on the percolation algorithms and writing some examples and it is inconsistent at the moment

**Comment by TomTranter** [comment]
@jgostick I had some issues with getting this to pass on travis. Eventually worked out the version of sympy that conda was using wasn't up to date and maybe had a bug in it. You might want to get Niloo to review the notebooks for percolation and my paper recreation. Should also teach her how to use MixedIP and maybe she can take on that project for Marios if it still needs doing. I'm willing to give advice and help. Hopefully this is all good to go

**Pull request merged**
