### PR TITLE
Cone model for hydraulic conductance

### PR DESCRIPTION
**Pull request by magnaou**
Cone model for hydraulic conductance.

### CODE REVIEW

**Review by ma-sadeghi — CHANGES_REQUESTED** [review]
@magnaou Can you please add unit tests for this?

**Comment by magnaou** [comment]
yes, sure

**Review by ma-sadeghi — DISMISSED** [review]
@magnaou Looks great.

**Comment by jgostick** [comment]
How does this PR affect the conical frustrum that Niloo is working on, as per #1421

**Comment by magnaou** [comment]
> How does this PR affect the conical frustrum that Niloo is working on, as per #1421

This model shouldn't take any shape factor as we discussed before.

**Comment by ma-sadeghi** [comment]
@jgostick @magnaou Shouldn't this be a shape factor model, rather than a conductance model?

**Comment by magnaou** [comment]
No, it is a formal derivation of an analytical solution of a Stokes flow problem in a cone. Equivalent to Hagen-Poiseuille but in a cone instead of a cylinder.

**Comment by ma-sadeghi** [comment]
> No, it is a formal derivation of an analytical solution of a Stokes flow problem in a cone. Equivalent to Hagen-Poiseuille but in a cone instead of a cylinder.

Yes, but other shape factor models are the same. They're formal derivation of analytical solution of Stokes flow for a particular cross-section. For example, `ball_and_stick` flow shape factor model is assuming spherical shape for pores and cylinders for throats.

**Comment by magnaou** [comment]
> > No, it is a formal derivation of an analytical solution of a Stokes flow problem in a cone. Equivalent to Hagen-Poiseuille but in a cone instead of a cylinder.
> 
> Yes, but other shape factor models are the same. They're formal derivation of analytical solution of Stokes flow for a particular cross-section. For example, `ball_and_stick` flow shape factor model is assuming spherical shape for pores and cylinders for throats.

I didn't thoroughly investigate what we have on the "shape_factor" models for flow. I know what they do, of course. However, the solutions I get using these models is different from what I get with the cone model in this PR. Which means they are different? I also have comparisons with experimental data and DNS on sphere packs and this cone model is giving the best accuracy. I can show you the results if you are interested. It's part of the collaboration with Antonio.

**Comment by magnaou** [comment]
Don't merge yet. To be discussed with @jgostick and @ma-sadeghi during the marathon or before.

**Comment by ma-sadeghi** [comment]
> > > No, it is a formal derivation of an analytical solution of a Stokes flow problem in a cone. Equivalent to Hagen-Poiseuille but in a cone instead of a cylinder.
> > 
> > 
> > Yes, but other shape factor models are the same. They're formal derivation of analytical solution of Stokes flow for a particular cross-section. For example, `ball_and_stick` flow shape factor model is assuming spherical shape for pores and cylinders for throats.
> 
> I didn't thoroughly investigate what we have on the "shape_factor" models for flow. I know what they do, of course. However, the solutions I get using these models is different from what I get with the cone model in this PR. Which means they are different? I also have comparisons with experimental data and DNS on sphere packs and this cone model is giving the best accuracy. I can show you the results if you are interested. It's part of the collaboration with Antonio.

I didn't mean that this is identical to other shape factors. I meant this should a shape factor model, and not a conductance model. If I remember correctly, the way our shape factors are set up is such that the baseline is assuming cylinders in series, and the shape factor needs to correct for that baseline.

**Comment by magnaou** [comment]
> > > > No, it is a formal derivation of an analytical solution of a Stokes flow problem in a cone. Equivalent to Hagen-Poiseuille but in a cone instead of a cylinder.
> > > 
> > > 
> > > Yes, but other shape factor models are the same. They're formal derivation of analytical solution of Stokes flow for a particular cross-section. For example, `ball_and_stick` flow shape factor model is assuming spherical shape for pores and cylinders for throats.
> > 
> > 
> > I didn't thoroughly investigate what we have on the "shape_factor" models for flow. I know what they do, of course. However, the solutions I get using these models is different from what I get with the cone model in this PR. Which means they are different? I also have comparisons with experimental data and DNS on sphere packs and this cone model is giving the best accuracy. I can show you the results if you are interested. It's part of the collaboration with Antonio.
> 
> I didn't mean that this is identical to other shape factors. I meant this should a shape factor model, and not a conductance model. If I remember correctly, the way our shape factors are set up is such that the baseline is assuming cylinders in series, and the shape factor needs to correct for that baseline.

Ok, I see what you mean @ma-sadeghi . In this PR, the baseline is a cone (not a cylinder) and shape factors are 1 (i.e., no shape factor correction). To be discussed during a teleconference I guess...

**Comment by ma-sadeghi** [comment]
Being addressed in PR #1604

**Pull request closed without merging**
