### PR TITLE
Add shale oil conductance example

### PR DESCRIPTION
**Pull request by xu-kai-xu**
I write a shale oil conductance example in the `contrib` directory.

### CODE REVIEW

**Comment by jgostick** [comment]
Hi @xu-kai-xu, why did you close this PR?  We'd love to add examples to the contrib folder and will work with you to help you get it passing the tests.

**Comment by xu-kai-xu** [comment]
@jgostick, hi, I meet a problem. there are two commits in my repo. i only need to push the second commit to the source dev. but i do not know how to finish this. so i close it. the first commit is the one when i sync my folk with the source dev. I am afraid it will trouble you.

**Comment by xu-kai-xu** [comment]
hi, @jgostick , I guess I can reopen this pr. The first commit is from the operation of sync my fork with the dev repo. The second is my shale oil example. If any problem, let me know. Thanks.

**Comment by xu-kai-xu** [comment]
This example is doing well on version 2.5. But on version 2.8, it needs some modifications.

**Pull request closed without merging**
