### PR TITLE
Fix __str__ methods

### PR DESCRIPTION
**Pull request by bspellio**
During my PEP8ification of OpenPNM I broke a few string methods. This PR should that as well as doing an extra check when initializing a `ModelWraper`.
@maghighi @jgostick

### CODE REVIEW

**Comment by jgostick** [comment]
This doesn't seem right.  I haven't run it, but the changes to models dict seem a bit drastic, and what about Core, and the printable dict/lists?

**Comment by jgostick** [comment]
Core prints fine, sorry about that...print printable lists don't

**Comment by bspellio** [comment]
@jgostick The reason for the change is that `__str__` is supposed to return a string, not call print many times.

**Comment by jgostick** [comment]
OK, understood.

**Comment by jgostick** [comment]
Perhaps all of the __str__ methods should be converted to return a string?

**Comment by bspellio** [comment]
They absolutely should be. I'll add that to this PR.

**Comment by bspellio** [comment]
@jgostick good to merge this?

**Comment by jgostick** [comment]
ok

**Pull request merged**
