### PR TITLE
Instantiate Physics with no Phase

### PR DESCRIPTION
**Pull request by jgostick**
I have updated the ModelsMixin class to catch all ``Exceptions`` and set model to deferred instead throwing an exception.  This means that instantiating a class when things are not quite setup properly is still possible, allowing the user to manually fix things afterwards, like create associations between Physics and Phases.  This change will actually help with classes where models are added but cannot be run.  Before this change we only caught a KeyError exception, if a dependent property was not found.

### CODE REVIEW

**Comment by jgostick** [comment]
We need to have a group discussion about this.  The way I've implemented things, all 'exceptions' that occur when adding a model are caught, the model is added but not run, and the regen_mode is set to 'deferred'.  My thought was that an error message is issued, which includes the exception message, so the use can then go fix the problem.  This way the code can still run and be 'responsive', rather than halting fatally...but I wonder if it's a bad idea to have a program that appears to be running but is actually in a 'broken' state?

**Comment by jgostick** [comment]
Interestingly, we could solve this problem by implementing the idea that @ma-sadeghi mentioned this morning in #1670.  If we had more specialized exceptions, then we could catch some of them and raise a warning, but let others fail?  I guess that begs the points, why have an exception if you don't plan to halt execution if it's found.

**Comment by ma-sadeghi** [comment]
I think letting the user write code that doesn't run might be dangerous, as they might go too far. Basically, I think fixing errors as soon as they appear is much easier than fixing an entire program that's broken on too many fronts. 

Another advantage of not letting users write broken code is that they can "learn" how to write proper OpenPNM code as they write small snippets that occasionally fail to run. Anyways, just my opinion.

**Comment by jgostick** [comment]
Investigate the 'freeze_models' setting to see if that helps.

**Comment by jgostick** [comment]
Fixes #1671

**Comment by jgostick** [comment]
This version sets ``phys.settings['freeze_models'] = True`` if ``phase=None``.  This solves the problem perfectly, except the user now needs to 'unfreeze' the models.  I have added a warning message to the `regenerate_props` method to inform the user of the situation...this is the best we can do I think.  If this passes all tests, then it can be merged.  The changes were very simple in the end.

**Comment by ma-sadeghi** [comment]
> This version sets `phys.settings['freeze_models'] = True` if `phase=None`. This solves the problem perfectly, except the user now needs to 'unfreeze' the models. I have added a warning message to the `regenerate_props` method to inform the user of the situation...this is the best we can do I think. If this passes all tests, then it can be merged. The changes were very simple in the end.

Can we add a helper method that "unfreezes" all models? and let the user know in the warning message to call that method when they're done.

**Comment by jgostick** [comment]
We could do something like:

```
if phase is None:
    self.settings['freeze_models'] = True

# Do rest of init here:

if phase is None:
    self.settings['freeze_models'] = False

```

**Comment by ma-sadeghi** [comment]
> We could do something like:
> 
> ```
> if phase is None:
>     self.settings['freeze_models'] = True
> 
> # Do rest of init here:
> 
> if phase is None:
>     self.settings['freeze_models'] = False
> ```

Sounds like a good idea. Maybe also add a comment explaining why we do this, as a note to future self.

**Comment by jgostick** [comment]
Sorry, this doesn't work.  We'd have to add this at the super.__init__ level, which gets called before the subclassed stuff runs, which is where all the models are.  Unless....maybe python has a magic method that gets called 'after' a subclass is finished with it's own init?

**Comment by ma-sadeghi** [comment]
> Sorry, this doesn't work. We'd have to add this at the super.**init** level, which gets called before the subclassed stuff runs, which is where all the models are. Unless....maybe python has a magic method that gets called 'after' a subclass is finished with it's own init?

Is this relevant by any chance? ([source](https://stackoverflow.com/questions/16017397/injecting-function-call-after-init-with-decorator))
```python
# define a new metaclass which overrides the "__call__" function
class NewInitCaller(type):
    def __call__(cls, *args, **kwargs):
        """Called when you call MyNewClass() """
        obj = type.__call__(cls, *args, **kwargs)
        obj.new_init()
        return obj


# then create a new class with the __metaclass__ set as our custom metaclass
class MyNewClass(object):
    __metaclass__ = NewInitCaller
    def __init__(self):
        print "Init class"
    def new_init(self):
        print "New init!!"

# when you create an instance
a = MyNewClass()
>>> Init class
>>> New init!!
```

**Comment by jgostick** [comment]
Technically that is 'the' solution (or the python 3 version), but I feel like this would make subclassing the Generic classes very complicated.  A user would have to pass in the metaclass and call it.  Might as well just add ``if phase is None: self.settings['freeze_models']`` to each new subclass.  

I actually spent 30 mins skimming through old rejected PEPs to see if anyone has proposed a ``__post__`` method that get called after each ``__init__``.  I couldn't really tell from the pep titles, but it looks like not.

**Comment by ma-sadeghi** [comment]
> Technically that is 'the' solution (or the python 3 version), but I feel like this would make subclassing the Generic classes very complicated. A user would have to pass in the metaclass and call it. Might as well just add `if phase is None: self.settings['freeze_models']` to each new subclass.
> 
> I actually spent 30 mins skimming through old rejected PEPs to see if anyone has proposed a `__post__` method that get called after each `__init__`. I couldn't really tell from the pep titles, but it looks like not.

Do you think it would be a bad idea if we manually "unfreeze" the models when the user calls `alg.run()`?

**Pull request merged**
