### PR TITLE
Adding Continuous Integration with TravisCI

### PR DESCRIPTION
**Pull request by bspellio**
In this PR I've added a few things that I feel will aid development of OpenPNM.

First, I've added TravisCI as our continuous integration client. Continuous integration allows for the automation of building and testing OpenPNM through specifications defined in `.travis.yml`. Now, whenever someone opens a pull request, TravisCI will runs tests against the state of that current branch and inform everyone whether or not is is safe to merge.

Second, I've modified `setup.py` so that it explicitly states the requirements of `OpenPNM` so that they can be easily installed via `python setup.py install`.

Finally, I've added a `.gitignore` to help with accidental commits of unwanted files, such as `.pyc` or `.egg`

Please Review: @jgostick

### CODE REVIEW

**Comment by bspellio** [comment]
I should mention that when I ran the test suite locally, quite a few of them failed.

**Comment by jgostick** [comment]
Ahhh, the .gitignore file :-)  We've had battles about why this shouldn't
be in the git repo.   I guess since James have moved on to bigger and
better things we can reopen the issue.  :-D  I never did understand why he
had such a problem with it.

Anyway, great stuff, thanks for getting this started!

**Comment by jgostick** [comment]
I actually removed the scipy dependency because it tried installing scipy (compiling it) from source, which is a terrible thing.  We'll have to figure that out.  We have a check in the package init that errors if sp>0.14 is not found.

**Comment by bspellio** [comment]
So TravisCI is building properly, but the tests are failing still. I think this may need to be addressed in a separate PR.

**Comment by bspellio** [comment]
So I've made it such that TravisCI is now failing properly when tests fail. That being said, we have a lot of test failures on this branch. I've rebased off of the latest version of the `develop` branch, but I'm still seeing failures. Thoughts on this?

**Comment by jgostick** [comment]
There are about 9-10 tests that fail due to docstrings that don't output
the expected format.

**Comment by bspellio** [comment]
>There are about 9-10 tests that fail due to docstrings that don't output
the expected format.

Looks like there's about 18 failures, with a lot of errors. I'd recommend us figuring out these failures before building out anything else. It's not great to have a branch always failing.

**Comment by jgostick** [comment]
Agreed!  That's your job this summer :-)

**Comment by bspellio** [comment]
Okay so I'll merge these changes and then I'll begin to debug all of these tests.

**Pull request merged**
