### PR TITLE
Powerlaw model for hydraulic conductance

### PR DESCRIPTION
**Pull request by magnaou**
- Fix the truncated power law model to match Antonio's experimental results
- Added the cone model to non Newtonian

### CODE REVIEW

**Review by ma-sadeghi — CHANGES_REQUESTED** [review]
@magnaou Can you please add unit tests?

**Comment by magnaou** [comment]
yep!

**Review by ma-sadeghi — CHANGES_REQUESTED** [review]
Nevermind.

**Review by ma-sadeghi — APPROVED** [review]

**Comment by magnaou** [comment]
put the effective viscosity model outside.

**Comment by ma-sadeghi** [comment]
Being addressed in PR #1604

**Pull request closed without merging**
