### PR TITLE
Fix plot_conns and plot_coords

### LINKED ISSUE #1626: [Bug]: Plot_connections in 3D has problem with scaling
**Describe the bug**
3D network's plot_connection does not work properly

https://github.com/PMEAL/OpenPNM/blob/fbb4a8d7a0204f4d85ceff3a6d112a11d7e2b02d/openpnm/topotools/plottools.py#L250 
https://github.com/PMEAL/OpenPNM/blob/fbb4a8d7a0204f4d85ceff3a6d112a11d7e2b02d/openpnm/topotools/plottools.py#L289

**To Reproduce**
```python
import numpy as np
import openpnm as op
import matplotlib.pyplot as plt
from openpnm import topotools
pn = op.network.Cubic(shape=[5, 8, 3])
op.topotools.plot_connections(pn)

```

image
 - Autoscale doesn't work properly in 3D

### PR DESCRIPTION
**Pull request by Ni2M**
Fixes #1626 
- plot coords has problem with auto_scale
- plot_conns has problem with overwriting figures (if an already existing figure is fed into the algorithm it can not rescale the axes)

### CODE REVIEW

**Comment by Ni2M** [comment]
The problem with auto_scale in plot_coords: ax.autoscale_view() instead.
The problem with overwriting figures in plot_conns: using ax.relim()
## Using ax.relim and plt.auto_scale
image
image
plot top face in fig, use fig to plot bottom face as well
image
## using ax.relim and ax.autoscale_view
image
image
plot top face in fig, use fig to plot bottom face as well
image

The problem with overwriting figures was because the datalims are based on the Ps.coords not all the pores in the network. So when a limit for axes in pores=top is calculated, the same figure could not be used to show the limit for axes in pores=bottom. refer to line https://github.com/PMEAL/OpenPNM/blob/f1dc180d0a346f8b58254c6d16b9ebee99581bc7/openpnm/topotools/plottools.py#L230 and those pores come from line https://github.com/PMEAL/OpenPNM/blob/f1dc180d0a346f8b58254c6d16b9ebee99581bc7/openpnm/topotools/plottools.py#L212

**Comment by ma-sadeghi** [comment]
@Ni2M Was this PR done?

**Comment by jgostick** [comment]
I'm sorry, I thought Niloo had told me during our 1-on-1 that it was done...but maybe I was mistaken.

**Comment by ma-sadeghi** [comment]
> I'm sorry, I thought Niloo had told me during our 1-on-1 that it was done...but maybe I was mistaken.

It probably is, I was just making sure because of this commit message:

> 3D problem fixed, 2D plot_conn is problematic

@Ni2M Could you please confirm?

**Comment by Ni2M** [comment]
@ma-sadeghi I apologize I did not check my notifies. Yes, the PR was done. The problem was with 2D and 3D parts that I wrote an if condition to separate the problems. Thank you very much @ma-sadeghi @jgostick for your time and consideration.

**Comment by Ni2M** [comment]
```python
import numpy as np
import openpnm as op
import matplotlib.pyplot as plt
from openpnm import topotools
pn = op.network.Cubic(shape=[8, 10, 10])
op.topotools.plot_connections(pn)
op.topotools.plot_coordinates(pn, pores=pn.Ps,  c='r')
fig=op.topotools.plot_coordinates(pn, pores=pn.pores('pore.left'))
op.topotools.plot_coordinates(pn, pores=pn.pores('pore.right'),fig=fig,c='c')
```
image
image
image

```python
import numpy as np
import openpnm as op
import matplotlib.pyplot as plt
from openpnm import topotools
pn = op.network.Cubic(shape=[10, 10, 1])
op.topotools.plot_connections(pn)
op.topotools.plot_coordinates(pn, pores=pn.Ps,  c='r')
fig = op.topotools.plot_networkx(pn)
fig=op.topotools.plot_coordinates(pn, pores=pn.pores('pore.left'))
op.topotools.plot_coordinates(pn, pores=pn.pores('pore.right'),fig=fig,c='c')
```
image
image
image
image

**Comment by ma-sadeghi** [comment]
@Ni2M Looks great! Well done!

**Pull request merged**
