### PR TITLE
Metrics finalize

### PR DESCRIPTION
**Pull request by Ni2M**
I had the chance to overview these old file and they worked well. This is the improved version of metrics rel perm. The init file in dev didn't have importing for metrics, so I changed that part, too. There was something wrong with other files before that prevented us from merging this new metrics algorithm. It's mostly similar to the previous one, but additional parts related to handling the results and xyz directions are added. We already have an improved notebook example related to this improved file so it would be good if we can merge it with dev.

### CODE REVIEW

**Comment by Ni2M** [comment]
This PR is an improved version of relperm metrics (handling xyz directions, changes in results and outputs). The current version of relperm metrics in [dev metrics](https://github.com/PMEAL/OpenPNM/blob/dev/openpnm/algorithms/metrics/RelativePermeability.py) is also usable, but it is better to be replaced by this improved version with more functionalities. The example provided in example galore will be based on this new version.

**Comment by Ni2M** [comment]
This branch is ready to merge. It will activate metrics import in init file and replace the current relperm file.

**Review by ma-sadeghi — CHANGES_REQUESTED** [review]
@Ni2M Could you please add a unit test for 2D cases as well? Thanks

**Comment by Ni2M** [comment]
Yes, sure.

**Comment by Ni2M** [comment]
I added a test to see if the code automatically realizes the input network is 2D and gives results for only 2 directions. @ma-sadeghi could you please review if this PR is ready to merge? Thank you.

**Review by ma-sadeghi — APPROVED** [review]

**Comment by ma-sadeghi** [comment]
> I added a test to see if the code automatically realizes the input network is 2D and gives results for only 2 directions. @ma-sadeghi could you please review if this PR is ready to merge? Thank you.

Looks good.

**Comment by Ni2M** [comment]
Thank you @ma-sadeghi for your help and adjusting the test files. That looks better now. Thanks.

**Pull request merged**
