### PR TITLE
Remove Shortcuts & Graphics

### PR DESCRIPTION
**Pull request by bspellio**
Do we have any objections for removing `Shortcuts` and `Graphics` from the code base? Shortcuts is not once imported or used though out the entire package, and Graphics depends on Python 2.7 which we are not supporting.

cc/ @jgostick

### CODE REVIEW

**Comment by jgostick** [comment]
We should also remove the Graphic class, as this uses VTK, which is Python 2.7 only, and OpenPNM is 3+ only.  I never wanted to support heavy visualization anyway.

**Comment by bspellio** [comment]
Great I'll add that to this PR

**Comment by bspellio** [comment]
There are other parts of code that require that Graphics class and it is actually exposed to the user. Making it a breaking change. We should perhaps deprecate it for now?

**Comment by jgostick** [comment]
The only parts of the code are the 'run script' that I know of.  Seriously, it's python 2.7, so it's already broken.

**Pull request merged**
